package main

const httpGenVersion = "v0.0.1"

const versionComment = `
// Code generated by protoc-gen-go-ghttp. DO NOT EDIT.
// versions:
// 	protoc-gen-go-http {{.ghttp_version}}
// 	protoc             {{.protoc_version}}
// source: {{.source_path}}`

const methodMessageStruct = `
type {{.message_name}} struct {
	{{- range .fields}}
		{{.}}
	{{- end}}
}
`
